trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: GoTool@0
  displayName: 'Use Go 1.15'
  inputs:
    version: 1.15

- task: Go@0
  displayName: 'go build'
  inputs:
    command: build
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
