name: 'Go Web App Testing'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: GoWebAPI Test
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Snyk CLI to check for security issues
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
    
    - name: Snyk Auth
      run: snyk auth ${{ secrets.snykToken }}
    
    - name: Snyk SCA Go
      run: snyk test --org=${{ secrets.snykOrg }}

    - name: Snyk SAST
      run: snyk code test --org=${{ secrets.snykOrg }}

    - name: Build a Docker image to test for vulnerabilities
      working-directory: webappsfortesting/gowebapi
      run: docker build -t gowebapi .
      
    - name: Snyk Container monitor
      run: snyk container test gowebapi --file=.
